CONSOLE-4083: Remove Dockerfile.builder and make other container file changes

diff --git a/Dockerfile.plugins.demo b/Dockerfile.plugins.demo
--- a/Dockerfile.plugins.demo
+++ b/Dockerfile.plugins.demo
@@ -3,7 +3,38 @@
 # See dynamic-demo-plugin/README.md for details.
 
 # Stage 0: build the demo plugin
-FROM quay.io/coreos/tectonic-console-builder:v26 AS build
+FROM registry.ci.openshift.org/ocp/builder:rhel-9-base-nodejs-openshift-4.17 AS nodebuilder
+
+ADD . .
+
+USER 0
+
+ARG YARN_VERSION=v1.22.19
+
+# bootstrap yarn so we can install and run the other tools.
+RUN CACHED_YARN=./artifacts/yarn-${YARN_VERSION}.tar.gz; \
+    if [ -f ${CACHED_YARN} ]; then \
+    npm install ${CACHED_YARN}; \
+    else \
+    npm install https://github.com/yarnpkg/yarn/releases/download/${YARN_VERSION}/yarn-${YARN_VERSION}.tar.gz; \
+    fi
+
+# The REMOTE_SOURCES value is set by the build system to indicate the location of the cachito-backed artifacts cache.
+# As cachito might not be available in all environments, we need to make sure the value is set before trying to use it and
+# that the COPY layer below doesn't fail. Setting it to be the Dockerfile itself is fairly safe, as it will always be
+# available.
+ARG REMOTE_SOURCES=./Dockerfile.product
+ARG REMOTE_SOURCE_DIR=/tmp/remote-sources
+
+COPY $REMOTE_SOURCES $REMOTE_SOURCES_DIR
+
+# use dependencies provided by Cachito
+RUN test -d ${REMOTE_SOURCES}/cachito-gomod-with-deps || exit 0; \
+    cp -f $REMOTE_SOURCES_DIR/cachito-gomod-with-deps/app/registry-ca.pem . \
+    && cp -f $REMOTE_SOURCES_DIR/cachito-gomod-with-deps/app/frontend/{.npmrc,.yarnrc,yarn.lock} frontend/
+
+# prevent download of cypress binary as part of module installs
+ENV CYPRESS_INSTALL_BINARY=0
 
 RUN mkdir -p /src/console
 COPY . /src/console
@@ -16,16 +47,16 @@ RUN yarn install && \
     yarn build
 
 # Stage 1: build the target image
-FROM node:10
+FROM node:18
 
-COPY --from=build /src/console/dynamic-demo-plugin/dist /opt/console-plugin-demo/static
-COPY --from=build /src/console/dynamic-demo-plugin/node_modules /opt/console-plugin-demo/node_modules
-COPY --from=build /src/console/dynamic-demo-plugin/http-server.sh /opt/console-plugin-demo/http-server.sh
+COPY --from=nodebuilder /src/console/dynamic-demo-plugin/dist /opt/console-plugin-demo/static
+COPY --from=nodebuilder /src/console/dynamic-demo-plugin/node_modules /opt/console-plugin-demo/node_modules
+COPY --from=nodebuilder /src/console/dynamic-demo-plugin/http-server.sh /opt/console-plugin-demo/http-server.sh
 
 LABEL io.k8s.display-name="OpenShift Console Demo Plugin" \
-      io.k8s.description="Sample OpenShift Console dynamic plugin used for testing purposes." \
-      io.openshift.tags="openshift" \
-      maintainer="Vojtech Szocs <vszocs@redhat.com>"
+    io.k8s.description="Sample OpenShift Console dynamic plugin used for testing purposes." \
+    io.openshift.tags="openshift" \
+    maintainer="Vojtech Szocs <vszocs@redhat.com>"
 
 USER 1001
 
